package ru.zarina.zarina.ui.theme.rework

import androidx.compose.ui.graphics.Color

// Names are generated by https://chir.ag/projects/name-that-color/
object Colors {
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
    val MineShaftLight = Color(0xFF383838)
    val MineShaftDark = Color(0xFF232323)
    val WildSand = Color(0xFFF5F5F5)
    val Scorpion = Color(0xFF585858)
    val Gray = Color(0xFF8C8C8C)
    val Gallery = Color(0xFFEAEAEA)
    val SilverChalice = Color(0xFFA1A1A1)
    val AltoLight = Color(0xFFE0E0E0)
    val AltoDark = Color(0xFFD5D5D5)
}
