[versions]
# Plugins
androidGradlePlugin = "8.7.3"
googlePlayServices-plugin = "4.4.2"
firebase-crashlyticsPlugin = "3.0.2"
androidGitVersion = "0.4.14"
checkDependencyUpdates = "1.5.0"

kotlin = "2.1.0"
kotlin-ksp = "2.1.0-1.0.29"
kotlin-coroutines = "1.9.0"
kotlin-serialization = "1.7.3"
kotlin-immutableCollections = "0.3.8"

jetpack-core = "1.15.0"
jetpack-appcompat = "1.7.0"
jetpack-lifecycle = "2.8.7"
jetpack-activity = "1.9.3"
jetpack-navigation = "2.8.5"
jetpack-datastore = "1.1.1"
jetpack-room = "2.6.1"
jetpack-splashScreen = "1.0.1"
jetpack-media3 = "1.5.1"
jetpack-paging = "3.3.5"
jetpack-security-cripto = "1.0.0"
jetpack-browser = "1.8.0"
jetpack-junit = "1.2.1"
jetpack-uiAutomator = "2.3.0"
jetpack-espresso = "3.6.1"
jetpack-benchmark = "1.3.3"
jetpack-credentials = "1.5.0-beta01"
jetpack-webkit = "1.12.1"
jetpack-annotation = "1.9.1"

jetpack-compose-bom = "2024.12.01"
jetpack-compose-material-navigation = "1.7.6"

ktor = "3.0.3"

dagger = "2.53.1"
hilt-navigationCompose = "1.2.0"

accompanist = "0.36.0"

coil = "2.7.0"
composeShimmer = "1.3.1"
qrcode = "4.1.1"

libphonenumber = "8.13.48"

timber = "5.0.1"
leakCanary = "2.14"

googlePlayServices-location = "21.3.0"
googlePlayServices-maps = "19.0.0"
googlePlayServices-maps-compose = "6.4.0"
googlePlayServices-auth-api-phone = "18.1.0"

recaptcha = "18.6.1"

firebase-bom = "33.7.0"

firebase-performance = "1.4.2"
mindbox = "2.11.2"

junit = "4.13.2"

lint-composeChecks = "1.4.2"

coreLibraryDesugaring = "2.1.3"


[libraries]
# Jetpack
jetpack-core = { group = "androidx.core", name = "core-ktx", version.ref = "jetpack-core" }
jetpack-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "jetpack-appcompat" }
jetpack-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "jetpack-activity" }
jetpack-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "jetpack-activity" }
jetpack-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "jetpack-lifecycle" }
jetpack-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetpack-lifecycle" }
jetpack-lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "jetpack-lifecycle" }
jetpack-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "jetpack-lifecycle" }
jetpack-lifecycle-viewModel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "jetpack-lifecycle" }
jetpack-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "jetpack-navigation" }
jetpack-dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "jetpack-datastore" }
jetpack-room = { group = "androidx.room", name = "room-ktx", version.ref = "jetpack-room" }
jetpack-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "jetpack-room" }
jetpack-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "jetpack-splashScreen" }
jetpack-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "jetpack-media3" }
jetpack-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "jetpack-media3" }
jetpack-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "jetpack-paging" }
jetpack-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "jetpack-paging" }
jetpack-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "jetpack-security-cripto" }
jetpack-browser = { group = "androidx.browser", name = "browser", version.ref = "jetpack-browser" }
jetpack-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "jetpack-junit" }
jetpack-test-uiAutomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "jetpack-uiAutomator" }
jetpack-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "jetpack-espresso" }
jetpack-benchmark = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "jetpack-benchmark" }
jetpack-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "jetpack-credentials" }
jetpack-credentials-compat = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "jetpack-credentials" }
jetpack-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "jetpack-webkit" }
jetpack-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "jetpack-annotation" }

# Jetpack Compose
jetpack-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "jetpack-compose-bom" }
jetpack-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
jetpack-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
jetpack-compose-ui = { group = "androidx.compose.ui", name = "ui" }
jetpack-compose-animation = { group = "androidx.compose.animation", name = "animation" }
jetpack-compose-material = { group = "androidx.compose.material", name = "material" }
jetpack-compose-material-navigation = { group = "androidx.compose.material", name = "material-navigation", version.ref = "jetpack-compose-material-navigation" }
jetpack-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
jetpack-compose-toolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
jetpack-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
jetpack-compose-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
jetpack-compose-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Kotlin
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-googlePlayServices = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-immutableCollections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlin-immutableCollections" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
hilt-navigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigationCompose" }

dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

accompanist-systemUi = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-navigationMaterial = { group = "com.google.accompanist", name = "accompanist-navigation-material", version.ref = "accompanist" }
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
composeShimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "composeShimmer" }
qrcode = { group = "io.github.g0dkar", name = "qrcode-kotlin", version.ref = "qrcode" }

libphonenumber = { group = "io.michaelrocks", name = "libphonenumber-android", version.ref = "libphonenumber" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
leakCanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }

googlePlayServices-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "googlePlayServices-location" }
googlePlayServices-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "googlePlayServices-maps" }
googlePlayServices-maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "googlePlayServices-maps-compose" }
googlePlayServices-maps-compose-utils = { group = "com.google.maps.android", name = "maps-compose-utils", version.ref = "googlePlayServices-maps-compose" }
googlePlayServices-auth-api-phone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "googlePlayServices-auth-api-phone" }

recaptcha = { group = "com.google.android.recaptcha", name = "recaptcha", version.ref = "recaptcha" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }

mindbox = { group = "cloud.mindbox", name = "mobile-sdk", version.ref = "mindbox" }
mindbox-firebase = { group = "cloud.mindbox", name = "mindbox-firebase" }

java-inject = { module = "javax.inject:javax.inject", version = "1" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

lint-composeChecks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "lint-composeChecks" }

coreLibraryDesugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "coreLibraryDesugaring" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
googlePlayServices = { id = "com.google.gms.google-services", version.ref = "googlePlayServices-plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlyticsPlugin" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-performance" }
androidGitVersion = { id = "com.gladed.androidgitversion", version.ref = "androidGitVersion" }
checkDependencyUpdates = { id = "name.remal.check-dependency-updates", version.ref = "checkDependencyUpdates" }
