[versions]
android-gradle = "8.1.0-alpha11"
kotlin = "1.8.20"
androidx-core = "1.10.0"
androidx-lifecycle = "2.6.1"
androidx-activity = "1.7.0"
androidx-splashScreen = "1.0.0"
androidx-navigation = "2.5.3"
compose = "2023.04.00"
accompanist = "0.30.1"
hilt = "2.44.2"
hilt-compose-navigation = "1.0.0"
google-play-services-plugin = "4.3.15"
firebase = "31.4.0"
firebase-crashlytics = "2.9.4"
firebase-performance = "1.4.2"
gitVersioning = "0.4.14"

junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-benchmark = "1.1.1"
androidx-uiautomator = "2.2.0"
espresso = "3.5.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashScreen" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-ui-core = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-core = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
accompanist-systemUi = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose-navigation" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-uiautomator" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-benchmark = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-test = { id = "com.android.test", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-play-services = { id = "com.google.gms.google-services", version.ref = "google-play-services-plugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-performance" }
gitVersioning = { id = "com.gladed.androidgitversion", version.ref = "gitVersioning" }

[bundles]

