package ru.zarina.zarina.ui.theme

import androidx.compose.ui.graphics.Color

// Names are generated by https://chir.ag/projects/name-that-color/
data object Colors {
    val White = Color(0xFFFFFFFF)
    val Black = Color(0xFF000000)
    val MineShaftLight = Color(0xFF383838)
    val MineShaftDark = Color(0xFF232323)
    val WildSand = Color(0xFFF5F5F5)
}

// TODO: [Low] Remove!
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val Aluminium = Color(0xFFAAADB4)
val Mercury = Color(0xFFE7E5E5)
val Mineshaft = Color(0xFF373737)
val Monza = Color(0xFFDA0025)
val RollingStone = Color(0xFF727577)
val SolidPink = Color(0xFF983C4B)
