package ru.livetyping.zarina.core.uikit.impl.theme

import androidx.compose.ui.graphics.Color

// TODO: [Top] Rename after full migration

// Names are generated by https://chir.ag/projects/name-that-color/
internal object Colors2 {
    val MineShaft = Color(0xFF232323)
    val Gray = Color(0xFF817F7F)
    val White = Color.White
    val Gallery = Color(0xFFF0F0F0)
    val Alabaster = Color(0xFFF9F9F9)
    val TorchRed = Color(0xFFFF1A1A)
    val Mongoose = Color(0xFFBC9E84)
    val Emperor = Color(0xFF525252)
    val Mercury = Color(0xFFE7E5E5)
    val Pampas = Color(0xFFEEE9E5)
    val PampasLight = Color(0xFFF8F5F3)
}
