package ru.livetyping.zarina.core.uikit.impl.theme

import androidx.compose.ui.graphics.Color

// Names are generated by https://chir.ag/projects/name-that-color/
internal object Colors {
    val White = Color.White
    val MineShaftLight = Color(0xFF383838)
    val MineShaftDark = Color(0xFF232323)
    val WildSand = Color(0xFFF5F5F5)
    val Scorpion = Color(0xFF585858)
    val Gray = Color(0xFF8C8C8C)
    val Gallery = Color(0xFFEAEAEA)
    val SilverChalice = Color(0xFFA1A1A1)
    val AltoLight = Color(0xFFE0E0E0)
    val AltoDark = Color(0xFFD5D5D5)
    val Boulder = Color(0xFF777777)
    val Scarlet = Color(0xFFFF1B10)
    val VividTangerine = Color(0xFFFF8984)
    val Silver = Color(0xFFC0C0C0)
    val CuriousBlue = Color(0xFF2D9CDB)
    val FunGreen = Color(0xFF008A27)
    val Flamenco = Color(0xFFFF800B)
    val Chardon = Color(0xFFFFF3F1)
}
